from PIL import Image
img = Image.open("images.jpg")
#img.show()
#print(img.mode)
#img = img.convert("L")
#img.save("images.jpg")
#img = img.rotate(-90)
#img.show()
#print(img.size)
#print(img.width)
#print(img.height)
#img = img.resize((300,300))
copy = img.resize((150,150))
img.paste(copy,(100,100))
#box = (150,150,200,200)
#img = img.crop(box)
img.show()
